/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Ankit
 * Created : 02/17/2014 11:05:14
 */

package com.ankit.dto;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.ValueGenerationType;
import org.hibernate.type.VersionType;


@Entity
@Table(name="Address")
public class Address {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long addressId;
	private String street;
	private String city;
	private String country;
	@Version
	private Integer version;
	
	
	
	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 *
	 * getter method for street
	 * @return
	 *
	 */
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	/**
	 *
	 * getter method for city
	 * @return
	 *
	 */
	public String getCity() {
		return this.city;
	}

	/**
	 *
	 * setter method for city
	 * @param city
	 *
	 */
	public void setCity(final String city) {
		this.city = city;
	}

	/**
	 *
	 * getter method for country
	 * @return
	 *
	 */
	public String getCountry() {
		return this.country;
	}

	/**
	 *
	 * setter method for country
	 * @param country
	 *
	 */
	public void setCountry(final String country) {
		this.country = country;
	}

	/**
	 *
	 * getter method for addressId
	 * @return
	 *
	 */
	public long getAddressId() {
		return this.addressId;
	}

	/**
	 *
	 * setter method for addressId
	 * @param addressId
	 *
	 */
	public void setAddressId(final long addressId) {
		this.addressId = addressId;
	}

	@Override
	public String toString() {
		return "Address [addressId=" + addressId + ", street=" + street
				+ ", city=" + city + ", country=" + country + ", version="
				+ version + "]";
	}
	
}
